# Generated by Django 3.1 on 2020-08-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200825_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='experience',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
    ]
